### ISSUE TITLE
tunnels with subdomain specified start timing out at some point

### ISSUE THREAD

**Issue by johnksawers** [defunctzombie/localtunnel#55]
Hi there. I've just encountered an issue. I've been using the same subdomain for a few weeks now, on an off. Over the last two days I've started to get timeouts connecting to that subdomain. Here is my tunnel command:

    lt --port 80 --subdomain localsso --local_host privia.dev

If I kill the tunnel and restart it, it sometimes begins working again, and if I specify no subdomain, or another subdomain things work as expected. Also things start working again after the tunnel has been down overnight (I don't have more specifics on the timeline yet).

The timeout error I'm seeing is from nginx, not from my server.

**Comment by quarterto** [comment]
Just ran into this myself. It possibly happened after I killed and restarted the client a few times quickly?

**Comment by atomical** [comment]
I'm seeing this as well.

**Comment by jhubert** [comment]
Yup, here as well. Tunnel stopped responding so I killed it and then requested the same subdomain. Just kept getting 504 responses until I generated a new subdomain.

**Comment by zeevl** [comment]
Was running into this as well.   Started up my own instance of the [localtunnel-server](https://github.com/defunctzombie/localtunnel-server) to try to debug, but I've been unable to reproduce there so it could be an issue specifically with the localtunnel.me server.

**Comment by defunctzombie** [comment]
I think this happens because the localtunnel-server dies or has some other error. I need to debug why some errors cause the server to die and restart.

**Comment by zeevl** [comment]
Turns out running localtunnel-server on my own server didn't quite solve it, just delayed it.

I was, however, able to track this down to the fact that the client was quietly killing the sockets after some amount of time, so when the server tries to push down requests, they're never acknowledged and the pool eventually gets consumed.  

The above PR calls `remote.setKeepAlive(true)`.   With this fix, tunnels have remained open for over a week!
