### ISSUE TITLE
Unable to use CNAME

### ISSUE THREAD

**Issue by kingavinesh** [defunctzombie/localtunnel#78]
So I started localtunnel with --subdomain **abcd**  parameter. [**abcd** is just an example]

Now I can access my local server at *abcd.localtunnel.me* but since I already own a domain, I thought I wound create a CNAME record so that *xyz.mydomain.com* would open *abcd.localtunnel.com*

I went DNS settings of my domain and created a CNAME record and put value as
>**xyz**.mydomain.com

and 

> **abcd**.localtunnel.me 

So technically if I open xyz.mydomain.com, it should show the content the way it would show if someone would open abcd.localtunnel.me normally.

But when I actually opened xyz.mydomain.com it said :
*localtunnel error: no active client for '**xyz**'*

But when I created CNAME record for abcd.mydomain.com , it worked perfectly fine.

So that means subdomain of my own domain should match with subdomain of localtunnel. That means if I my localtunnel subdomain is "pqr" then my custom subdomain also should be "pqr" else it won't work.

How to make it work,  So that no matter what value of my custom subdomain is, it should always open *abcd.localtunnel.me* ?

**Comment by defunctzombie** [comment]
You cannot make this work because the subdomains must match (as you have discovered yourself) because this is how localtunnel knows which client to use. In this case, DNS is only used for IP resolution and your browser actually still sends the HOST header of `xyz.mydomain.com` to the IP address returned from the DNS lookup for `abcd.localtunnel.me`. So the subdomain is `xyz` not `abcd`. If your domain registrar supports url-redirects instead of CNAME then it might work.

On a more general thought, I wouldn't advise trying to use localtunnel in this way. The subdomains are not meant to be permanent.
